//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Web3SolanaFederation.Web3SolanaFederation"/> </summary
    public sealed class Web3SolanaFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedLogin<Web3FederationCommon.Web3SolanaIdentity>, Beamable.Common.ISupportsFederatedInventory<Web3FederationCommon.Web3SolanaIdentity>
    {
        
        public Web3SolanaFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Web3SolanaFederation";
            }
        }
    }
    
    internal sealed class MicroserviceParametersWeb3SolanaFederationClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForWeb3SolanaFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<Web3SolanaFederationClient>();
        }
        
        public static Web3SolanaFederationClient Web3SolanaFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<Web3SolanaFederationClient>();
        }
    }
}
